// admin actions
export const GET_TARGET_COORDINATES_FROM_CAMERA = 'GET_TARGET_COORDINATES_FROM_CAMERA';
export const SET_TARGET_COORDINATES = 'SET_TARGET_COORDINATES';
export const SET_TARGET_CUP_X = 'SET_TARGET_CUP_X';
export const SET_TARGET_CUP_Y = 'SET_TARGET_CUP_Y';
export const SET_LAUNCH_AFTER_TARGET_LOCK = 'SET_LAUNCH_AFTER_TARGET_LOCK';
export const LAUNCH = 'LAUNCH';
export const SET_THETA = 'SET_THETA';
export const SET_PHI   = 'SET_PHI';
export const GET_JOKE  = 'GET_JOKE';
export const GET_CHUCK_NORRIS_JOKE  = 'GET_CHUCK_NORRIS_JOKE';
export const SEND_DATA_TO_BOT = "SEND_DATA_TO_BOT";
export const CUP_MADE = 'CUP_MADE';
export const SET_POINT_FOR = 'SET_POINT_FOR';
export const SET_CUP_INDEX = 'SET_CUP_INDEX';
export const SET_MOTOR_SPEED_PERCENT = 'SET_MOTOR_SPEED_PERCENT';
export const STOP_MOTORS = 'STOP_MOTORS';

// play actions
export const REMOVE_CUP = 'REMOVE_CUP';
